### PR TITLE
[tests] Add `-Wno-implicit-function-declaration` for LTP build

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Currently used version of LTP has a bug that results in the following build error, e.g. when using Clang v18 on Ubuntu 24.04:

    clone301.c:136:8: error: call to undeclared function 'pidfd_send_signal'

This is because Clang promoted "implicit function declaration" check from a warning to an error starting from Clang v16. This commit adds `-Wno-implicit-function-declaration` flag to CFLAGS during LTP build.

Newer LTP releases fixed this bug, so in the future, when Gramine uses newer LTP, this commit should be reverted.

Reported by @woju.

## How to test this PR? 

Build LTP with Clang on Ubuntu 24.04.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2005)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2005)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/2005#-O7ZYsULD84HM43eQsWc:-O7ZYsULD84HM43eQsWd:b-cntjdf) (no related file):*
This problem only related to Clang. GCC on Ubuntu 24.04 builds fine. Proof:

- LTP build with Clang 18.1
```
/home/sdp/gramine/libos/test/ltp/src/testcases/kernel/syscalls/clone3/clone301.c:136:8: error: call to undeclared function 'pidfd_send_signal'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  136 |                 TEST(pidfd_send_signal(pidfd, CHILD_SIGNAL, &uinfo, 0));
```

- LTP build with GCC 13.2
```
/home/sdp/gramine/libos/test/ltp/src/testcases/kernel/syscalls/clone3/clone301.c: In function ‘run’:
/home/sdp/gramine/libos/test/ltp/src/testcases/kernel/syscalls/clone3/clone301.c:136:22: warning: implicit declaration of function ‘pidfd_send_signal’; did you mean ‘SYS_pidfd_send_signal’? [-Wimplicit-function-declaration]
  136 |                 TEST(pidfd_send_signal(pidfd, CHILD_SIGNAL, &uinfo, 0));
```

___

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2005)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2005)* status: all files reviewed, 1 unresolved discussion

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Direct-Sanitizers please (LTP test `clock_gettime04` failed with `CLOCK_REALTIME: Difference between successive readings greater than 5 ms`, seems like an unfortunate case of a VM's vCPU being descheduled for too long)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2005)* status: all files reviewed, 1 unresolved discussion

**Comment by dimakuv** [comment]
Jenkins, retest Jenkins-Direct-Sanitizers please (LTP test `clock_gettime04` failed again, same issue)

**Review by mkow — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/2005)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved
