### PR TITLE
[PAL,mbedtls] Fix build issues on newer Ubuntu and Clang

### PR DESCRIPTION
**Pull request by dimakuv**
## Description of the changes 

Two issues fixed:
- Unused for-loop variable `input_i` in `topo_info.c`
- Required ASN.1 dependencies for RSA in `mbedtls/config-pal.h`

This was detected on Ubuntu 24.04 and Clang 18. I don't know why I didn't observe this before; one of newer Ubuntu or Clang is the culprit.

Regarding the second issue, I also submitted an issue to mbedTLS team: https://github.com/Mbed-TLS/mbedtls/issues/9312

## How to test this PR? 

Build with Ubuntu 24.04 and Clang 18 (default on 24.04).

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1923)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1923)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramine/1923#-O0EcFPMCzD27a1hOos4:-O0EcFPMCzD27a1hOos5:bbvo67w) (no related file):*
FYI: don't forget to install `sudo apt install libomp-dev` for Clang, otherwise the `omp.c` LibOS test will fail with compilation error.

___

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1923)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramine/1923)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved
